# SPDX-FileCopyrightText: 2026 Michel Oosterhof <michel@oosterhof.net>
#
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import os
import posixpath
import re
from functools import lru_cache
from pathlib import Path

_COMMAND_NAME_RE = re.compile(r"^[A-Za-z0-9_.+-]{1,64}$")
_VERSIONED_COMMAND_RE = re.compile(
    r"^(?:python|python3|pip|pip3|gcc|g\+\+|clang|node|npm|php|perl|ruby|go|"
    r"java|javac|openssl|busybox)(?:[0-9][A-Za-z0-9.+-]*)?$"
)
_CHECKSUM_COMMAND_RE = re.compile(r"^(?:md5|sha1|sha224|sha256|sha384|sha512|b2)sum$")

_SHELL_RESERVED_WORDS = {
    "case",
    "do",
    "done",
    "elif",
    "else",
    "esac",
    "fi",
    "for",
    "function",
    "if",
    "in",
    "select",
    "then",
    "until",
    "while",
}

_KNOWN_LINUX_COMMANDS = {
    "ab",
    "addgroup",
    "adduser",
    "alias",
    "apache2",
    "apk",
    "apt",
    "apt-cache",
    "apt-get",
    "arch",
    "arp",
    "arping",
    "awk",
    "base32",
    "base64",
    "basename",
    "bash",
    "bg",
    "blkid",
    "bunzip2",
    "busybox",
    "bzcat",
    "bzip2",
    "cat",
    "cd",
    "chage",
    "chattr",
    "chgrp",
    "chkconfig",
    "chmod",
    "chown",
    "chpasswd",
    "chroot",
    "cksum",
    "clear",
    "cmp",
    "comm",
    "command",
    "cp",
    "cpio",
    "crontab",
    "curl",
    "cut",
    "dash",
    "date",
    "dd",
    "delgroup",
    "deluser",
    "df",
    "diff",
    "dig",
    "dirname",
    "dmesg",
    "dnf",
    "docker",
    "docker-compose",
    "dpkg",
    "du",
    "echo",
    "egrep",
    "env",
    "ethtool",
    "eval",
    "exec",
    "exit",
    "expand",
    "export",
    "expr",
    "false",
    "fdisk",
    "fgrep",
    "file",
    "find",
    "finger",
    "free",
    "ftp",
    "ftpget",
    "gcc",
    "gdb",
    "getent",
    "getfacl",
    "git",
    "grep",
    "groupadd",
    "groupdel",
    "groupmod",
    "groups",
    "gunzip",
    "gzip",
    "halt",
    "head",
    "help",
    "history",
    "host",
    "hostname",
    "htop",
    "id",
    "ifconfig",
    "insmod",
    "install",
    "iptables",
    "ip6tables",
    "ip",
    "journalctl",
    "kill",
    "killall",
    "last",
    "less",
    "ln",
    "locate",
    "login",
    "logname",
    "logout",
    "losetup",
    "ls",
    "lsattr",
    "lsblk",
    "lscpu",
    "lsmod",
    "lsof",
    "lspci",
    "make",
    "man",
    "md5sum",
    "mkdir",
    "mkfifo",
    "mknod",
    "mktemp",
    "modprobe",
    "more",
    "mount",
    "mv",
    "mysql",
    "nc",
    "nc.openbsd",
    "netcat",
    "netstat",
    "nice",
    "nl",
    "nohup",
    "nslookup",
    "openssl",
    "pacman",
    "passwd",
    "paste",
    "perl",
    "pgrep",
    "php",
    "pidof",
    "ping",
    "ping6",
    "pip",
    "pip3",
    "pkill",
    "poweroff",
    "printf",
    "ps",
    "psql",
    "pstree",
    "pwd",
    "python",
    "python2",
    "python3",
    "read",
    "readlink",
    "reboot",
    "redis-cli",
    "renice",
    "reset",
    "rm",
    "rmdir",
    "route",
    "rpm",
    "rsync",
    "run-parts",
    "scp",
    "screen",
    "sed",
    "service",
    "set",
    "setfacl",
    "sftp",
    "sh",
    "sha1sum",
    "sha224sum",
    "sha256sum",
    "sha384sum",
    "sha512sum",
    "shutdown",
    "sleep",
    "sort",
    "sqlite3",
    "ss",
    "ssh",
    "stat",
    "strings",
    "su",
    "sudo",
    "sync",
    "sysctl",
    "systemctl",
    "tac",
    "tail",
    "tar",
    "tee",
    "telnet",
    "test",
    "tftp",
    "time",
    "timeout",
    "top",
    "touch",
    "tr",
    "traceroute",
    "true",
    "truncate",
    "tty",
    "type",
    "ulimit",
    "umask",
    "uname",
    "uniq",
    "unlink",
    "unshare",
    "unzip",
    "uptime",
    "useradd",
    "userdel",
    "usermod",
    "users",
    "vi",
    "vim",
    "w",
    "watch",
    "wc",
    "wget",
    "whereis",
    "which",
    "who",
    "whoami",
    "xargs",
    "xxd",
    "xz",
    "xzcat",
    "yes",
    "yum",
    "zcat",
    "zgrep",
    "zsh",
}


def normalize_command_name(command: str) -> str:
    return posixpath.basename(command.strip())


@lru_cache(maxsize=1)
def operator_allowlist() -> frozenset[str]:
    path = os.environ.get("ADAPTIVE_VALID_COMMANDS_FILE", "")
    if not path:
        return frozenset()
    try:
        lines = Path(path).read_text(encoding="utf-8").splitlines()
    except OSError:
        return frozenset()
    return frozenset(
        line.strip()
        for line in lines
        if line.strip() and not line.lstrip().startswith("#")
    )


def invalid_linux_command_reason(command: str) -> str | None:
    name = normalize_command_name(command)
    if not name:
        return "empty_command"
    if not _COMMAND_NAME_RE.fullmatch(name):
        return "invalid_command_name"
    if name in _SHELL_RESERVED_WORDS:
        return "shell_reserved_word"
    if (
        name not in _KNOWN_LINUX_COMMANDS
        and name not in operator_allowlist()
        and not _VERSIONED_COMMAND_RE.fullmatch(name)
        and not _CHECKSUM_COMMAND_RE.fullmatch(name)
    ):
        return "unknown_linux_command"
    return None
